version: '3'

### Service Network ############################################################
networks:
  public:
    external:
      name: ${PROJECT_EXTERNAL_NETWORK}
  backend:
    driver: bridge
  default:
    driver: bridge

services:
### API Service ############################################################
  api:
    image   : nginx:alpine
    labels:
      - traefik.enable=true
      - traefik.http.services.api-${PROJECT_NAME}.loadbalancer.server.port=80
      - traefik.http.routers.api-${PROJECT_NAME}.entrypoints=web-secure
      - traefik.http.routers.api-${PROJECT_NAME}.tls
      - traefik.http.routers.api-${PROJECT_NAME}.rule=Host(`api.${PROJECT_HOSTNAME}`)
    volumes :
      - ./containers/nginx/backend-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${BACKEND_DIR_HOST:-./backend}/:/var/www
    networks:
      - backend
      - public
    depends_on:
      - ${BACKEND_ENGINE:-php-fpm}
### Backend Service ############################################################
  php-fpm:
    image: ${PROJECT_NAME}-app
    build:
      context: ./containers/php
      args:
        - TIMEZONE=${TIMEZONE:-Asia/Jakarta}
        - PHP_VERSION=${PHP_VERSION:-7.4}
        ### Custom Install #####################################################
        - INSTALL_BCMATH=${INSTALL_BCMATH:-false}
        - INSTALL_BZIP=${INSTALL_BZIP:-false}
        - INSTALL_CALENDAR=${INSTALL_CALENDAR:-false}
        - INSTALL_COMPOSER=${INSTALL_COMPOSER:-false}
        - INSTALL_GD=${INSTALL_GD:-false}
        - INSTALL_GHOSTSCRIPT=${INSTALL_GHOSTSCRIPT:-false}
        - INSTALL_GMP=${INSTALL_GMP:-false}
        - INSTALL_ICONV=${INSTALL_ICONV:-false}
        - INSTALL_IMAGE_OPTIMIZERS=${INSTALL_IMAGE_OPTIMIZERS:-false}
        - INSTALL_IMAGEMAGICK=${INSTALL_IMAGEMAGICK:-false}
        - INSTALL_IMAP=${INSTALL_IMAP:-false}
        - INSTALL_INTL=${INSTALL_INTL:-false}
        - INSTALL_LDAP=${INSTALL_LDAP:-false}
        - INSTALL_MEMCACHED=${INSTALL_MEMCACHED:-false}
        - INSTALL_MONGO=${INSTALL_MONGO:-false}
        - INSTALL_MSSQL=${INSTALL_MSSQL:-false}
        - INSTALL_MYSQLI=${INSTALL_MYSQLI:-false}
        - INSTALL_OCI8=${INSTALL_OCI8:-false}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE:-false}
        - INSTALL_PCNTL=${INSTALL_PCNTL:-false}
        - INSTALL_PGSQL=${INSTALL_PGSQL:-false}
        - INSTALL_PHPDBG=${INSTALL_PHPDBG:-false}
        - INSTALL_PHPREDIS=${INSTALL_PHPREDIS:-false}
        - INSTALL_SUPERVISOR=${INSTALL_SUPERVISOR:-false}
        - INSTALL_SYMFONY=${INSTALL_SYMFONY:-false}
        - INSTALL_TOKENIZER=${INSTALL_TOKENIZER:-false}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG:-false}
        - INSTALL_ZIP_ARCHIVE=${INSTALL_ZIP_ARCHIVE:-false}
    networks:
      - backend
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/extra.d:/usr/local/etc/php/conf.d
    volumes:
      - ${BACKEND_DIR_HOST:-./backend}:/var/www
      - ./cache/composer/:/root/.composer/cache
      - ./containers/php/config.d:/usr/local/etc/php/extra.d
      - ./code-server/php/:/root/.vscode-server
  database:
    image: postgres:alpine
    networks:
      - backend
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ${DB_DATA_PATH:-./database/data}:/var/lib/postgresql/data:Z
  adminer:
    image: adminer
    labels:
      - traefik.enable=true
      - traefik.http.services.db-${PROJECT_NAME}.loadbalancer.server.port=8080
      - traefik.http.routers.db-${PROJECT_NAME}.entrypoints=web-secure
      - traefik.http.routers.db-${PROJECT_NAME}.tls
      - traefik.http.routers.db-${PROJECT_NAME}.rule=Host(`db.${PROJECT_HOSTNAME}`)
    networks:
      - backend
      - public
    environment:
     - ADMINER_DEFAULT_SERVER=database
    depends_on:
      - database