version: '3'

### Service Network ############################################################
networks:
  public:
    external:
      name: ${PROJECT_EXTERNAL_NETWORK:-caddy}
  backend:
    driver: bridge
  default:
    driver: bridge

services:
### Frontend Service ###########################################################
  frontend:
    image: ${COMPOSE_PROJECT_NAME}-frontend:${COMPOSE_PROJECT_VERSION:-1.0}
    build:
      context: ./containers/node
      args:
        - NODEJS_VERSION=${NODEJS_VERSION:-16.13}
        - ENABLE_COREPACK=${NODEJS_ENABLE_COREPACK:-false}
        ### OS Timezone
        - TIMEZONE=${NODEJS_TIMEZONE:-Asia/Jakarta}
    working_dir: /var/www/frontend
    expose:
      - 3000
    command: ${FRONTEND_COMMAND:-npx http-server -p 3000}
    volumes :
      - ./frontend:/var/www/frontend
      - ./.cache/frontend/pnpm:/root/.cache/pnpm
      - ./.cache/frontend/pnpm-store:/root/.pnpm-store
      - ./.git:/var/www/.git
      - ./.vscode-server/node:/root/.vscode-server
    networks:
      - public
    labels:
      caddy: ${COMPOSE_PROJECT_NAME}.localhost
      caddy.reverse_proxy: "{{upstreams 3000}}"

### API Service ################################################################
  api-server:
    depends_on:
      - php-fpm
    image   : ${COMPOSE_PROJECT_NAME}-caddy:${COMPOSE_PROJECT_VERSION:-1.0}
    build:
      context: ./containers/caddy
    labels:
      caddy: api.${COMPOSE_PROJECT_NAME}.localhost
      caddy.reverse_proxy: "{{upstreams}}"
    volumes :
      - ./backend:/var/www/backend
      - ./containers/php-fpm/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./storage/caddy/data:/data
      - ./storage/caddy/config:/config
    networks:
      - backend
      - public
  php-fpm:
    depends_on:
      - elasticsearch-node-a
      - database
    image: ${COMPOSE_PROJECT_NAME}-app:${COMPOSE_PROJECT_VERSION:-1.0}
    build:
      context: ./containers/php-fpm
      args:
        - TIMEZONE=${PHP_TIMEZONE:-Asia/Jakarta}
        - PHP_VERSION=${PHP_VERSION:-8.0}
        ### Custom Install #####################################################
        - INSTALL_BASH_COMPLETION=${PHP_INSTALL_BASH_COMPLETION:-false}
        - INSTALL_BCMATH=${PHP_INSTALL_BCMATH:-false}
        - INSTALL_BZIP=${PHP_INSTALL_BZIP:-false}
        - INSTALL_CALENDAR=${PHP_INSTALL_CALENDAR:-false}
        - INSTALL_COMPOSER=${PHP_INSTALL_COMPOSER:-false}
        - INSTALL_GD=${PHP_INSTALL_GD:-false}
        - INSTALL_GHOSTSCRIPT=${PHP_INSTALL_GHOSTSCRIPT:-false}
        - INSTALL_GMP=${PHP_INSTALL_GMP:-false}
        - INSTALL_ICONV=${PHP_INSTALL_ICONV:-false}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_INSTALL_IMAGE_OPTIMIZERS:-false}
        - INSTALL_IMAGEMAGICK=${PHP_INSTALL_IMAGEMAGICK:-false}
        - INSTALL_IMAP=${PHP_INSTALL_IMAP:-false}
        - INSTALL_INTL=${PHP_INSTALL_INTL:-false}
        - INSTALL_LDAP=${PHP_INSTALL_LDAP:-false}
        - INSTALL_MEMCACHED=${PHP_INSTALL_MEMCACHED:-false}
        - INSTALL_MONGO=${PHP_INSTALL_MONGO:-false}
        - INSTALL_MSSQL=${PHP_INSTALL_MSSQL:-false}
        - INSTALL_MYSQLI=${PHP_INSTALL_MYSQLI:-false}
        - INSTALL_NODEJS_LTS=${PHP_INSTALL_NODEJS_LTS:-false}
        - INSTALL_OCI8=${PHP_INSTALL_OCI8:-false}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE:-false}
        - INSTALL_PCNTL=${PHP_INSTALL_PCNTL:-false}
        - INSTALL_PGSQL=${PHP_INSTALL_PGSQL:-false}
        - INSTALL_PHPDBG=${PHP_INSTALL_PHPDBG:-false}
        - INSTALL_PHPREDIS=${PHP_INSTALL_PHPREDIS:-false}
        - INSTALL_SUPERVISOR=${PHP_INSTALL_SUPERVISOR:-false}
        - INSTALL_SYMFONY_CLI=${PHP_INSTALL_SYMFONY_CLI:-false}
        - INSTALL_TOKENIZER=${PHP_INSTALL_TOKENIZER:-false}
        - INSTALL_VIM=${PHP_INSTALL_VIM:-false}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG:-false}
        - INSTALL_ZIP_ARCHIVE=${PHP_INSTALL_ZIP_ARCHIVE:-false}
    working_dir: /var/www/backend
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/usr/local/etc/php/local.d
    volumes:
      - ./.cache/php-fpm/composer:/root/.composer/cache
      - ./.git:/var/www/.git
      - ./.vscode-server/php-fpm/:/root/.vscode-server
      - ./backend:/var/www/backend
      - ./containers/php-fpm/conf.d:/usr/local/etc/php/local.d
      - ./workspace/bashrc:/root/.bashrc
      - ./workspace/source.d:/root/source.d
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-certs:/var/www/elasticsearch-certs
      - ${WORKSPACE_GPG_DIR:-./workspace/gpg}:/root/.gnupg
      - ${WORKSPACE_SSH_DIR:-./workspace/ssh}:/root/.ssh
    networks:
      - backend

### Database Service ###########################################################
  database:
    image: postgres:${DB_VERSION:-14.1}-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ${DB_DATA_PATH:-./storage/database}:/var/lib/postgresql/data:Z
    networks:
      - backend
  adminer:
    image: adminer
    environment:
     - ADMINER_DEFAULT_SERVER=database
    networks:
      - backend
      - public
    depends_on:
      - database
    labels:
      caddy: db.${COMPOSE_PROJECT_NAME}.localhost
      caddy.reverse_proxy: "{{upstreams 8080}}"

### Search Service #############################################################
  elasticsearch-setup:
    image: elasticsearch:${ELASTIC_VERSION:-8.0.0}
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [[ ! -f config/certs/ca.zip ]]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [[ ! -f config/certs/certs.zip ]]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elasticsearch-node-a\n"\
          "    dns:\n"\
          "      - elasticsearch-node-a\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: elasticsearch-node-b\n"\
          "    dns:\n"\
          "      - elasticsearch-node-b\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        chown -R 1000:root /usr/share/elasticsearch-node-a;
        chown -R 1000:root /usr/share/elasticsearch-node-b;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        chmod 644 config/certs/ca/ca.crt;
        chmod 755 config/certs;
        chmod 755 config/certs/ca;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch-node-a:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://elasticsearch-node-a:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    volumes:
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-certs:/usr/share/elasticsearch/config/certs
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-node-a:/usr/share/elasticsearch-node-a
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-node-b:/usr/share/elasticsearch-node-b
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch-node-a/elasticsearch-node-a.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch-node-a:
    depends_on:
      elasticsearch-setup:
        condition: service_healthy
    image: elasticsearch:${ELASTIC_VERSION:-8.0.1}
    environment:
      - ES_SETTING_NODE_NAME=elasticsearch-node-a
      - ES_SETTING_BOOTSTRAP_MEMORY__LOCK=true
      - ES_SETTING_CLUSTER_NAME=${COMPOSE_PROJECT_NAME}-cluster
      - ES_SETTING_CLUSTER_INITIAL__MASTER__NODES=elasticsearch-node-a,elasticsearch-node-b
      - ES_SETTING_DISCOVERY_SEED__HOSTS=elasticsearch-node-b
      - ES_SETTING_XPACK_LICENSE_SELF__GENERATED_TYPE=basic
      - ES_SETTING_XPACK_SECURITY_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_KEY=certs/elasticsearch-node-a/elasticsearch-node-a.key
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_CERTIFICATE=certs/elasticsearch-node-a/elasticsearch-node-a.crt
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_CERTIFICATE__AUTHORITIES=certs/ca/ca.crt
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_VERIFICATION__MODE=certificate
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_KEY=certs/elasticsearch-node-a/elasticsearch-node-a.key
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE=certs/elasticsearch-node-a/elasticsearch-node-a.crt
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE__AUTHORITIES=certs/ca/ca.crt
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_VERIFICATION__MODE=certificate
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-certs:/usr/share/elasticsearch/config/certs
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-node-a:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: ${ELASTIC_CPU_LIMIT:-0.50}
          memory: ${ELASTIC_MEMORY_LIMIT:-3072M}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  elasticsearch-node-b:
    depends_on:
      - elasticsearch-node-a
    image: elasticsearch:${ELASTIC_VERSION:-8.0.1}
    environment:
      - ES_SETTING_NODE_NAME=elasticsearch-node-b
      - ES_SETTING_BOOTSTRAP_MEMORY__LOCK=true
      - ES_SETTING_CLUSTER_NAME=${COMPOSE_PROJECT_NAME}-cluster
      - ES_SETTING_CLUSTER_INITIAL__MASTER__NODES=elasticsearch-node-a,elasticsearch-node-b
      - ES_SETTING_DISCOVERY_SEED__HOSTS=elasticsearch-node-a
      - ES_SETTING_XPACK_LICENSE_SELF__GENERATED_TYPE=basic
      - ES_SETTING_XPACK_SECURITY_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_KEY=certs/elasticsearch-node-b/elasticsearch-node-b.key
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_CERTIFICATE=certs/elasticsearch-node-b/elasticsearch-node-b.crt
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_CERTIFICATE__AUTHORITIES=certs/ca/ca.crt
      - ES_SETTING_XPACK_SECURITY_HTTP_SSL_VERIFICATION__MODE=certificate
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_ENABLED=true
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_KEY=certs/elasticsearch-node-b/elasticsearch-node-b.key
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE=certs/elasticsearch-node-b/elasticsearch-node-b.crt
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_CERTIFICATE__AUTHORITIES=certs/ca/ca.crt
      - ES_SETTING_XPACK_SECURITY_TRANSPORT_SSL_VERIFICATION__MODE=certificate
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-certs:/usr/share/elasticsearch/config/certs
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-node-b:/usr/share/elasticsearch/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: ${ELASTIC_CPU_LIMIT:-0.50}
          memory: ${ELASTIC_MEMORY_LIMIT:-3072M}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    depends_on:
      elasticsearch-node-a:
        condition: service_healthy
      elasticsearch-node-b:
        condition: service_healthy
    image: kibana:${ELASTIC_VERSION:-8.0.1}
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://elasticsearch-node-a:9200
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - SERVER_PUBLICBASEURL=https://kibana.${COMPOSE_PROJECT_NAME}.localhost
      - TELEMETRY_ENABLED=false
    volumes:
      - ${ELASTIC_DATA_PATH:-./storage/elasticsearch}-certs:/usr/share/kibana/config/certs
    networks:
      - backend
      - public
    deploy:
      resources:
        limits:
          cpus: ${ELASTIC_CPU_LIMIT:-0.50}
          memory: ${ELASTIC_MEMORY_LIMIT:-3072M}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    labels:
      caddy: kibana.${COMPOSE_PROJECT_NAME}.localhost
      caddy.reverse_proxy: "{{upstreams 5601}}"
